name:                consin
version:             0.1.0.0
github:              "dspies-leapyear/consin"
license:             BSD3
author:              "David Spies"
maintainer:          "david@leapyear.io"
copyright:           "2018 David Spies"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dspies-leapyear/consin#readme>

default-extensions:
- ConstraintKinds
- DataKinds
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeOperators
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- conkin
- conkin-extra
- constraints
- containers
- generic-deriving
- mtl
- pointless-fun
- singletons
- stream-reader
- template-haskell

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
- -Wredundant-constraints
