name:                persistwrap
version:             0.1.0.0
github:              "davidspies/persistwrap"
license:             BSD3
author:              "David Spies"
maintainer:          "dnspies@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/davidspies/persistwrap#readme>

dependencies:
- TypeCompose
- aeson
- base >= 4.7 && < 5
- bytestring
- conkin
- constraints
- containers
- dlist
- lens
- monad-extras
- mmorph
- mtl
- pointless-fun
- reflection
- singletons
- stm
- template-haskell
- text
- time
- transformers-base

default-extensions:
  ConstraintKinds
  DataKinds
  DefaultSignatures
  DeriveFunctor
  DeriveGeneric
  DuplicateRecordFields
  EmptyCase
  ExplicitNamespaces
  FlexibleContexts
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralizedNewtypeDeriving
  InstanceSigs
  KindSignatures
  LambdaCase
  MultiParamTypeClasses
  NamedFieldPuns
  OverloadedStrings
  RankNTypes
  RecordWildCards
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeApplications
  TypeFamilies
  TypeOperators
  TypeSynonymInstances
  ViewPatterns

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror

tests:
  persistwrap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - persistwrap
