name:                persistwrap-persistent
version:             0.1.0.0
github:              "dspies-leapyear/persistwrap-persistent"
license:             BSD3
author:              "David Spies"
maintainer:          "david@leapyear.io"
copyright:           "2018 David Spies"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dspies-leapyear/persistwrap-persistent#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- conkin
- conkin-extra
- consin
- constraints
- containers
- monad-logger
- mtl
- persistent
- persistent-sqlite
- persistent-template
- persistwrap
- persistwrap-primitives
- persistwrap-table
- reflection
- resource-pool
- singletons
- text
- unliftio-core

default-extensions:
- ConstraintKinds
- DataKinds
- DisambiguateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
- -Wredundant-constraints

tests:
  persistwrap-persistent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filepath
    - hspec
    - persistwrap-persistent
    - temporary
