name:                persistwrap
version:             0.1.0.0
github:              "dspies-leapyear/persistwrap"
license:             BSD3
author:              "David Spies"
maintainer:          "david@leapyear.io"
copyright:           "2018 David Spies"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dspies-leapyear/persistwrap#readme>

dependencies:
- TypeCompose
- base >= 4.7 && < 5
- conkin
- conkin-extra
- consin
- constraints
- containers
- mmorph
- mtl
- persistwrap-primitives
- persistwrap-structure
- persistwrap-table
- singletons
- stream-reader
- template-haskell
- text

default-extensions:
  ConstraintKinds
  DataKinds
  DefaultSignatures
  DeriveFunctor
  DeriveGeneric
  DuplicateRecordFields
  EmptyCase
  EmptyDataDeriving
  FlexibleContexts
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralizedNewtypeDeriving
  InstanceSigs
  KindSignatures
  LambdaCase
  MultiParamTypeClasses
  NamedFieldPuns
  OverloadedStrings
  RankNTypes
  RecordWildCards
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeApplications
  TypeFamilies
  TypeOperators
  TypeSynonymInstances
  ViewPatterns

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
- -Wredundant-constraints

tests:
  persistwrap-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - generic-deriving
    - hspec
    - persistwrap
    - pretty-show
    - tasty
    - tasty-discover
    - tasty-golden
    - tasty-hspec
    - tasty-quickcheck
